### PR TITLE
Tenzorum Grant Submission

### PR DESCRIPTION
**Pull request by pet3r-pan**

### CODE REVIEW

**Comment by markspereira** [comment]
Finalised grant proposal

**Comment by MareenG** [comment]
Hey @pet3r-pan , @MoritzNeto,  @markspereira and @dtbx 
Sorry, I had to revert the merging. I would like to ask you to comment a bit more on a few aspects of your proposal to get a better understanding of your project and the scope of it. 
Could you create a new pull request. 
Sorry for the inconvenience, 
Mareen

**Comment by dtbx** [comment]
Hey Mareen, Thanks for the feedback, we'll get a bit more details on the project's aspect and pull request again. 
Cheers, 
Daniel

**Comment by MareenG** [comment]
@dtbx thank you. 
It would be great to have a more granular set up of your milestones and a more defined description of your deliverables. It would be also great if you could provide some resources of prior projects you worked on, sth like your coding portfolio. 
Additionally, I would like to ask you to include the estimated funding you will ask for each of your milestone.I feel you ask for quite an high amount of funding. It would be great to understand for what steps you need the funding. Also is the range of grants we are giving out between $5.000 and $100.000. 
Looking forward to the iterated proposal
Mareen

**Comment by dtbx** [comment]
Hi @MareenG , we've revised the proposal and submitted a more detailed project milestones and deliverables description including cost estimate, timeline. As for our portfolio see below:

**Radek Ostrowski**, Architect and CTO - https://github.com/radek1st?tab=repositories also has been working with Sony Playstation team, lead big data projects in the banking sector, audited decentralized exchanges contracts, among others.

**Mark Pereira**, Full Stack Blockchain dev - https://github.com/markspereira?tab=repositories , Been working on VR projects, FinTech, and worked on Ethereum in the past year.

**Moritz Neto**, Product Manager - UX and design professional, developed viral content that ranks number 1 on google with no marketing budget and got translated to 5 languages (google: "how to issue a token" . and also "How to do ICO")

**Daniel Bar**, Project Manager - Founded the biggest crypto community in Australia 4 years ago (bitfwd.com), lead international collaboration with Chinese developer ecosystem. Worked as research Engineer in quantum nanoelectronics, semiconductor and finance industry consultancy.

Let us know if there are more questions we can answer.

Cheers,
Daniel

**Pull request merged**
